### ISSUE TITLE
Erro ao compilar com item vazio de lista

### ISSUE THREAD

**Issue by yzakius** [abntex/limarka#151]
**Comportamento esperado**:
Que o limarka compile mesmo se faltar algum item na lista.

**Passos para reprodução**:
Lista:
```
1. exemplo de item 1;
2. exemplo de item 2;
3. exemplo de item 3;
4.
```
Erro:

```
╰─$  limarka exec
Erro: /home/yzakius/.rvm/gems/ruby-2.4.0/gems/pandoc_abnt-1.1.2/lib/pandoc_abnt/lista_filter.rb:131:in `primeiro_tolken_do_item': undefined method `[]' for nil:NilClass (NoMethodError)
    from /home/yzakius/.rvm/gems/ruby-2.4.0/gems/pandoc_abnt-1.1.2/lib/pandoc_abnt/lista_filter.rb:85:in `block in processa_items_da_lista'
    from /home/yzakius/.rvm/gems/ruby-2.4.0/gems/pandoc_abnt-1.1.2/lib/pandoc_abnt/lista_filter.rb:80:in `each'
    from /home/yzakius/.rvm/gems/ruby-2.4.0/gems/pandoc_abnt-1.1.2/lib/pandoc_abnt/lista_filter.rb:80:in `processa_items_da_lista'
    from /home/yzakius/.rvm/gems/ruby-2.4.0/gems/pandoc_abnt-1.1.2/lib/pandoc_abnt/lista_filter.rb:62:in `block in filtra_json'
    from /home/yzakius/.rvm/gems/ruby-2.4.0/gems/pandoc_abnt-1.1.2/lib/pandoc_abnt/lista_filter.rb:60:in `each'
    from /home/yzakius/.rvm/gems/ruby-2.4.0/gems/pandoc_abnt-1.1.2/lib/pandoc_abnt/lista_filter.rb:60:in `filtra_json'
    from /home/yzakius/.rvm/gems/ruby-2.4.0/gems/pandoc_abnt-1.1.2/exe/pandoc_abnt:13:in `<top (required)>'
    from /home/yzakius/.rvm/gems/ruby-2.4.0/bin/pandoc_abnt:23:in `load'
    from /home/yzakius/.rvm/gems/ruby-2.4.0/bin/pandoc_abnt:23:in `<main>'
    from /home/yzakius/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
    from /home/yzakius/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
pandoc: Error running filter pandoc_abnt
Filter returned error status 1
```

**Especificações do sistema**:
limarka 0.7.2

**Comment by edusantana** [comment]
Na realidade esse erro é do pandoc_abnt.

**Comment by yzakius** [comment]
Então melhor reportar para outro local, certo?

**Comment by edusantana** [comment]
certo, [pandoc_abnt](https://github.com/limarka/pandoc_abnt/issues/)

**Comment by edusantana** [comment]
Este issue será fechado aqui pois ele é relativo ao pandoc_abnt, já cadastrei o issue lá.
