### ISSUE TITLE
erro ubuntu 19.04

### ISSUE THREAD

**Issue by ipassos** [abntex/limarka#203]
Traceback (most recent call last):
        12: from /usr/local/bin/limarka:23:in `<main>'
        11: from /usr/local/bin/limarka:23:in `load'
        10: from /var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/exe/limarka:10:in `<top (required)>'
         9: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
         8: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
         7: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
         6: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         5: from /var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/lib/limarka/cli.rb:57:in `exec'
         4: from /var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/lib/limarka/cli.rb:57:in `chdir'
         3: from /var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/lib/limarka/cli.rb:59:in `block in exec'
         2: from /var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/lib/limarka/trabalho.rb:120:in `atualiza_de_arquivos'
         1: from /var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/lib/limarka/trabalho.rb:141:in `ler_configuracao'
/var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/lib/limarka/trabalho.rb:151:in `ler_configuracao_pdf': uninitialized constant Limarka::Trabalho::PdfForms (NameError)

**Comment by ipassos** [comment]
Traceback (most recent call last):                                                                                                                                                           
        10: from /usr/local/bin/limarka:23:in `<main>'                                                                                                                                       
         9: from /usr/local/bin/limarka:23:in `load'                                                                                                                                         
         8: from /var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/exe/limarka:10:in `<top (required)>'                                                                                       
         7: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'                                                                                                         
         6: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'                                                                                                           
         5: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'                                                                                          
         4: from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'                                                                                                         
         3: from /var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/lib/limarka/cli.rb:57:in `exec'                                                                                            
         2: from /var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/lib/limarka/cli.rb:57:in `chdir'                                                                                           
         1: from /var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/lib/limarka/cli.rb:61:in `block in exec'                                                                                   
/var/lib/gems/2.5.0/gems/limarka-20.6.16.pre.361/lib/limarka/conversor.rb:41:in `convert': uninitialized constant Limarka::Conversor::Tempfile (NameError)
