### ISSUE TITLE
Apresentar mensagem de erro amigável quando executada fora do diretório do projeto

### ISSUE THREAD

**Issue by edusantana** [abntex/limarka#38]
A mensagem atual foi:

```
$ limarka 
/var/lib/gems/2.3.0/gems/limarka-0.2.0/lib/limarka/trabalho.rb:143:in `ler_configuracao_pdf': Arquivo não encontrado: configuracao.pdf (IOError)
	from /var/lib/gems/2.3.0/gems/limarka-0.2.0/lib/limarka/trabalho.rb:138:in `ler_configuracao'
	from /var/lib/gems/2.3.0/gems/limarka-0.2.0/lib/limarka/trabalho.rb:124:in `atualiza_de_arquivos'
	from /var/lib/gems/2.3.0/gems/limarka-0.2.0/lib/limarka/cli.rb:84:in `exec2'
	from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
	from /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
	from /var/lib/gems/2.3.0/gems/limarka-0.2.0/exe/limarka:6:in `<top (required)>'
	from /usr/local/bin/limarka:23:in `load'
	from /usr/local/bin/limarka:23:in `<main>'
```

**Comment by edusantana** [comment]
Foi implementado em algum commit.
